# Generated by Django 5.1.3 on 2025-05-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_companyseller_homeimage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="companyseller",
            options={
                "verbose_name": "فروشنده",
                "verbose_name_plural": "فروشندگان شرکت",
            },
        ),
        migrations.AddField(
            model_name="companyseller",
            name="vitrin_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="نام ویترین"
            ),
        ),
    ]
