# Generated by Django 5.1.3 on 2025-01-03 13:18

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0002_companyseller_homeimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyVault",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_balance",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="موجودی شرکت"
                    ),
                ),
                (
                    "company_assets",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="دارایی شرکت"
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="شرح")),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_type",
                    models.CharField(
                        choices=[
                            ("individual", "مشتری حقیقی"),
                            ("company", "شرکت"),
                            ("gallery", "گالری"),
                            ("supplier", "تأمین\u200cکننده"),
                        ],
                        max_length=20,
                        verbose_name="نوع مشتری",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="نام"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="نام خانوادگی",
                    ),
                ),
                (
                    "mellicode",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        unique=True,
                        verbose_name="کد ملی",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=11, null=True, verbose_name="شماره ثابت"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=11, null=True, verbose_name="تلفن همراه"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="شهر"
                    ),
                ),
                (
                    "code_posti",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="کدپستی"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="آدرس"
                    ),
                ),
                (
                    "total_gold_balance",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=20,
                        verbose_name="موجودی طلای مشتری",
                    ),
                ),
                (
                    "total_gold_reserve",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=20,
                        verbose_name="موجودی طلای امانی",
                    ),
                ),
            ],
            options={
                "verbose_name": "مشتری",
                "verbose_name_plural": "مشتریان",
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="نام"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="نام خانوادگی",
                    ),
                ),
                (
                    "mellicode",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="کد ملی"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=11, null=True, verbose_name="شماره ثابت"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=11, null=True, verbose_name="تلفن همراه"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="شهر"
                    ),
                ),
                (
                    "code_posti",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="کدپستی"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="آدرس"
                    ),
                ),
            ],
            options={
                "verbose_name": "تامین کننده",
                "verbose_name_plural": "تامین کنندگان",
            },
        ),
        migrations.CreateModel(
            name="BuyWholesalerInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gold_type",
                    models.CharField(
                        choices=[("craft", "زینتی"), ("melt", "آبشده")],
                        max_length=50,
                        verbose_name="نوع طلا",
                    ),
                ),
                (
                    "serial",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="سریال فاکتور",
                    ),
                ),
                (
                    "invoice_date",
                    django_jalali.db.models.jDateField(
                        blank=True, null=True, verbose_name="تاریخ فاکتور"
                    ),
                ),
                (
                    "qty",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="تعداد کالای فاکتور"
                    ),
                ),
                (
                    "net_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="وزن فاکتور",
                    ),
                ),
                (
                    "exchange_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="وزن تهاتر ازحساب",
                    ),
                ),
                (
                    "accessory_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="وزن با متعلقات فاکتور",
                    ),
                ),
                (
                    "invoice_dailyprice",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="نرخ روز طلا"
                    ),
                ),
                (
                    "invoice_price",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="مبلغ فاکتور"
                    ),
                ),
                (
                    "discount",
                    models.IntegerField(blank=True, null=True, verbose_name="تخفیف"),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="شرح")),
                (
                    "companyseller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.companyseller",
                        verbose_name="کارشناس فروش",
                    ),
                ),
                (
                    "vault",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whole_vault",
                        to="paniavault.companyvault",
                        verbose_name="ولت شرکت",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whole_supllier",
                        to="paniavault.supplier",
                        verbose_name="تأمین\u200cکننده",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BuyRawInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gold_type",
                    models.CharField(
                        choices=[("raw", "خام"), ("scrap", "قیچی")],
                        max_length=50,
                        verbose_name="نوع طلا",
                    ),
                ),
                (
                    "invoice_date",
                    django_jalali.db.models.jDateField(
                        blank=True, null=True, verbose_name="تاریخ فاکتور"
                    ),
                ),
                (
                    "net_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="وزن خالص فاکتور",
                    ),
                ),
                (
                    "invoice_dailyprice",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="نرخ روز طلا"
                    ),
                ),
                (
                    "invoice_price",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="مبلغ فاکتور"
                    ),
                ),
                (
                    "discount",
                    models.IntegerField(blank=True, null=True, verbose_name="تخفیف"),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="شرح")),
                (
                    "companyseller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.companyseller",
                        verbose_name="کارشناس فروش",
                    ),
                ),
                (
                    "vault",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raw_vault",
                        to="paniavault.companyvault",
                        verbose_name="ولت شرکت",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raw_supllier",
                        to="paniavault.supplier",
                        verbose_name="تأمین\u200cکننده",
                    ),
                ),
            ],
        ),
    ]
