# Generated by Django 5.1.3 on 2025-01-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("paniavault", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyvault",
            name="company_assets",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=20,
                null=True,
                verbose_name="دارایی شرکت",
            ),
        ),
        migrations.AlterField(
            model_name="companyvault",
            name="company_balance",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=20,
                null=True,
                verbose_name="موجودی شرکت",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="customer_type",
            field=models.CharField(
                choices=[("individual", "مشتری حقیقی"), ("company", "مشتری حقوقی")],
                max_length=20,
                verbose_name="نوع مشتری",
            ),
        ),
    ]
