# Generated by Django 5.1.3 on 2025-01-05 11:39

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("paniavault", "0002_alter_companyvault_company_assets_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buyrawinvoice",
            name="net_weight",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="وزن خالص فاکتور",
            ),
        ),
        migrations.AlterField(
            model_name="buyrawinvoice",
            name="vault",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="raw_vault",
                to="paniavault.companyvault",
                verbose_name="ولت شرکت",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="companyvault",
            name="company_assets",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                default=Decimal("0.00"),
                max_digits=20,
                null=True,
                verbose_name="دارایی شرکت",
            ),
        ),
        migrations.AlterField(
            model_name="companyvault",
            name="company_balance",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0.00"),
                max_digits=20,
                verbose_name="موجودی شرکت",
            ),
        ),
    ]
