# Generated by Django 5.1.3 on 2025-01-05 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("paniavault", "0003_alter_buyrawinvoice_net_weight_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buyrawinvoice",
            name="vault",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="raw_vault",
                to="paniavault.companyvault",
                verbose_name="ولت شرکت",
            ),
        ),
    ]
