# Generated by Django 5.1.3 on 2025-01-05 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("paniavault", "0004_alter_buyrawinvoice_vault"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buyrawinvoice",
            name="vault",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="raw_vault",
                to="paniavault.companyvault",
                verbose_name="ولت شرکت",
            ),
            preserve_default=False,
        ),
    ]
