# Generated by Django 5.1.3 on 2025-01-06 07:46

import django.db.models.deletion
import django_jalali.db.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("paniavault", "0005_alter_buyrawinvoice_vault"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="buyrawinvoice",
            options={
                "verbose_name": "فاکتور خریدطلای خام",
                "verbose_name_plural": "فاکتورهای خریدطلای خام",
            },
        ),
        migrations.CreateModel(
            name="ReciptMeltInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_date",
                    django_jalali.db.models.jDateField(
                        blank=True, null=True, verbose_name="تاریخ فاکتور"
                    ),
                ),
                (
                    "net_weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="وزن خالص فاکتور",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="melt_supllier",
                        to="paniavault.supplier",
                        verbose_name="تأمین\u200cکننده",
                    ),
                ),
                (
                    "vault",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="melt_vault",
                        to="paniavault.companyvault",
                        verbose_name="ولت شرکت",
                    ),
                ),
            ],
            options={
                "verbose_name": "فاکتور تحویل آبشده",
                "verbose_name_plural": "فاکتورهای تحویل آبشده",
            },
        ),
    ]
