# Generated by Django 5.1.3 on 2025-01-06 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("paniavault", "0006_alter_buyrawinvoice_options_reciptmeltinvoice"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeltPiece",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="وزن قطعه"
                    ),
                ),
                (
                    "karat",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="عیارقطعه"
                    ),
                ),
                (
                    "ang_number",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="شماره انگ"
                    ),
                ),
                (
                    "lab_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="نام آزمایشگاه",
                    ),
                ),
                (
                    "additional_info",
                    models.TextField(
                        blank=True, null=True, verbose_name="اطلاعات اضافی"
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pieces",
                        to="paniavault.reciptmeltinvoice",
                        verbose_name="فاکتور",
                    ),
                ),
            ],
        ),
    ]
