# Generated by Django 5.1.3 on 2025-01-08 05:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("paniavault", "0007_meltpiece"),
    ]

    operations = [
        migrations.AddField(
            model_name="buyrawinvoice",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="تاریخ ایجاد"
            ),
        ),
        migrations.AddField(
            model_name="companyvault",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="تاریخ ایجاد"
            ),
        ),
        migrations.AddField(
            model_name="companyvault",
            name="updated_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="تاریخ به\u200cروزرسانی"
            ),
        ),
        migrations.AddField(
            model_name="meltpiece",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="تاریخ ایجاد"
            ),
        ),
        migrations.AddField(
            model_name="reciptmeltinvoice",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="تاریخ ایجاد"
            ),
        ),
    ]
