# Generated by Django 5.1.3 on 2025-01-08 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "paniavault",
            "0008_buyrawinvoice_created_at_companyvault_created_at_and_more",
        ),
        ("vitrin", "0002_vitrinvault"),
    ]

    operations = [
        migrations.AddField(
            model_name="meltpiece",
            name="code",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                unique=True,
                verbose_name="کد کار",
            ),
        ),
        migrations.AddField(
            model_name="meltpiece",
            name="is_sold",
            field=models.BooleanField(default=False, verbose_name="وضعیت فروش"),
        ),
        migrations.AddField(
            model_name="meltpiece",
            name="vitrin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="melt_vitrin",
                to="vitrin.vitrinvault",
                verbose_name="ویترین",
            ),
        ),
    ]
