# Generated by Django 5.1.3 on 2025-01-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("paniavault", "0010_meltpiece_net_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="reciptmeltinvoice",
            name="invoice_serial",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="سریال فاکتور"
            ),
        ),
        migrations.AlterField(
            model_name="meltpiece",
            name="karat",
            field=models.DecimalField(
                decimal_places=0, max_digits=3, verbose_name="عیارقطعه"
            ),
        ),
    ]
