# Generated by Django 5.1.3 on 2025-01-09 05:23

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_companyseller_homeimage"),
        ("paniavault", "0012_reciptmeltinvoice_melt_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyvault",
            name="vitrin_type",
            field=models.CharField(
                blank=True,
                choices=[("vault", "ولت"), ("vitrin", "بجستان"), ("safebox", "تهران")],
                max_length=20,
                null=True,
                verbose_name="نوع ویترین",
            ),
        ),
        migrations.AlterField(
            model_name="meltpiece",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pieces",
                to="paniavault.reciptmeltinvoice",
                verbose_name="فاکتور بنکدار",
            ),
        ),
        migrations.AlterField(
            model_name="meltpiece",
            name="vitrin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="melt_vitrin",
                to="paniavault.companyvault",
                verbose_name="ویترین",
            ),
        ),
        migrations.AlterField(
            model_name="reciptmeltinvoice",
            name="melt_type",
            field=models.CharField(
                blank=True,
                choices=[("vault", "برداشت از ولت"), ("scrap", "تهاترباقیچی")],
                max_length=50,
                null=True,
                verbose_name="روش تامین",
            ),
        ),
        migrations.CreateModel(
            name="ReciptCraftInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gold_type",
                    models.CharField(
                        choices=[
                            ("vault", "برداشت از ولت"),
                            ("melt", "تهاتر با آبشده"),
                            ("both", "هردو"),
                        ],
                        max_length=50,
                        verbose_name="نوع پرداخت",
                    ),
                ),
                (
                    "serial",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="سریال فاکتور",
                    ),
                ),
                (
                    "invoice_date",
                    django_jalali.db.models.jDateField(
                        blank=True, null=True, verbose_name="تاریخ فاکتور"
                    ),
                ),
                (
                    "qty",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="تعداد کالای فاکتور"
                    ),
                ),
                (
                    "net_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="وزن خرید فاکتور",
                    ),
                ),
                (
                    "accessory_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="وزن خریدبا متعلقات فاکتور",
                    ),
                ),
                (
                    "invoice_dailyprice",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="نرخ روز طلا"
                    ),
                ),
                (
                    "invoice_price",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="مبلغ فاکتور"
                    ),
                ),
                (
                    "discount",
                    models.IntegerField(blank=True, null=True, verbose_name="تخفیف"),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="شرح")),
                (
                    "companyseller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.companyseller",
                        verbose_name="کارشناس شرکت",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whole_supllier",
                        to="paniavault.supplier",
                        verbose_name="تأمین\u200cکننده",
                    ),
                ),
                (
                    "vault",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whole_vault",
                        to="paniavault.companyvault",
                        verbose_name="ولت شرکت",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="BuyWholesalerInvoice",
        ),
    ]
