# Generated by Django 5.1.3 on 2025-01-09 06:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("paniavault", "0014_rename_serial_reciptcraftinvoice_invoice_serial_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reciptcraftinvoice",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="تاریخ ایجاد"
            ),
        ),
        migrations.AlterField(
            model_name="reciptcraftinvoice",
            name="invoice_serial",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="سریال فاکتور"
            ),
        ),
    ]
