# Generated by Django 5.1.3 on 2025-01-09 14:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("paniavault", "0015_reciptcraftinvoice_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reciptcraftinvoice",
            options={
                "verbose_name": "فاکتور خرید زینتی",
                "verbose_name_plural": "فاکتورهای خرید زینتی",
            },
        ),
        migrations.RemoveField(
            model_name="companyvault",
            name="vitrin_type",
        ),
        migrations.DeleteModel(
            name="MeltPiece",
        ),
    ]
