# Generated by Django 5.1.3 on 2025-01-10 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("paniavault", "0017_alter_customer_customer_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buyrawinvoice",
            name="vault",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="raw_vault",
                to="paniavault.companyvault",
                verbose_name="ولت شرکت",
            ),
        ),
    ]
