# Generated by Django 5.1.3 on 2025-01-15 11:33

import django.db.models.deletion
import django.utils.timezone
import django_jalali.db.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_companyseller_homeimage"),
        ("paniavault", "0018_alter_buyrawinvoice_vault"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuyScrapInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_date",
                    django_jalali.db.models.jDateField(
                        blank=True, null=True, verbose_name="تاریخ فاکتور"
                    ),
                ),
                (
                    "net_weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="وزن ترازو",
                    ),
                ),
                (
                    "karat_weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="وزن عیار 740",
                    ),
                ),
                (
                    "invoice_dailyprice",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="نرخ روز طلا"
                    ),
                ),
                (
                    "invoice_price",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="مبلغ فاکتور"
                    ),
                ),
                (
                    "discount",
                    models.IntegerField(blank=True, null=True, verbose_name="تخفیف"),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="شرح")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاریخ ایجاد"
                    ),
                ),
                (
                    "companyseller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.companyseller",
                        verbose_name="کارشناس فروش",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scrap_customer",
                        to="paniavault.customer",
                        verbose_name="تأمین\u200cکننده",
                    ),
                ),
                (
                    "vault",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scrap_vault",
                        to="paniavault.companyvault",
                        verbose_name="ولت شرکت",
                    ),
                ),
            ],
            options={
                "verbose_name": "فاکتور خریدطلای قیچی",
                "verbose_name_plural": "فاکتورهای خریدطلای قیچی",
            },
        ),
    ]
