# Generated by Django 5.1.3 on 2025-01-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("paniavault", "0019_buyscrapinvoice"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="buyrawinvoice",
            options={
                "verbose_name": "خرید طلای خام",
                "verbose_name_plural": "خریدهای طلای خام",
            },
        ),
        migrations.AlterModelOptions(
            name="buyscrapinvoice",
            options={
                "verbose_name": "خرید طلای قیچی",
                "verbose_name_plural": "خریدهای طلای قیچی",
            },
        ),
        migrations.RemoveField(
            model_name="buyrawinvoice",
            name="gold_type",
        ),
        migrations.AlterField(
            model_name="buyscrapinvoice",
            name="karat_weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="وزن عیار 740",
            ),
        ),
    ]
