# Generated by Django 5.1.3 on 2025-01-16 04:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("paniavault", "0020_alter_buyrawinvoice_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="melliserail",
            field=models.CharField(
                blank=True,
                max_length=11,
                null=True,
                unique=True,
                verbose_name="شناسه ملی شرکت",
            ),
        ),
    ]
