# Generated by Django 5.1.3 on 2025-01-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("paniavault", "0021_customer_melliserail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="address",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="آدرس"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="code_posti",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="کدپستی"
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="address",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="آدرس"
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="code_posti",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="کدپستی"
            ),
        ),
    ]
