# Generated by Django 5.1.3 on 2025-04-07 18:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "paniavault",
            "0022_alter_customer_address_alter_customer_code_posti_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="buyrawinvoice",
            options={
                "verbose_name": "تامین طلای خام",
                "verbose_name_plural": "تامین های طلای خام",
            },
        ),
        migrations.AlterModelOptions(
            name="buyscrapinvoice",
            options={
                "verbose_name": "فاکتور تامین قیچی",
                "verbose_name_plural": "فاکتورهای تامین قیچی",
            },
        ),
        migrations.AlterModelOptions(
            name="reciptcraftinvoice",
            options={
                "verbose_name": "فاکتور تامین زینتی",
                "verbose_name_plural": "فاکتورهای تامین زینتی",
            },
        ),
        migrations.AlterModelOptions(
            name="reciptmeltinvoice",
            options={
                "verbose_name": "فاکتور تامین آبشده",
                "verbose_name_plural": "فاکتورهای تامین آبشده",
            },
        ),
    ]
