# Generated by Django 5.1.3 on 2025-04-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("paniavault", "0023_alter_buyrawinvoice_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="buyrawinvoice",
            name="supply_type",
            field=models.CharField(
                choices=[("gallery", "گالری"), ("platform", "پلتفرم")],
                default="gallery",
                max_length=15,
                verbose_name="نوع تأمین",
            ),
        ),
    ]
