# Generated by Django 5.1.3 on 2025-05-14 18:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("paniavault", "0026_piecetransfer_is_received_piecetransfer_is_sent_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PieceTransfer",
        ),
    ]
