# Generated by Django 5.1.3 on 2025-01-03 13:18

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0002_companyseller_homeimage"),
        ("paniavault", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SaleInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sale_date",
                    django_jalali.db.models.jDateField(
                        blank=True, null=True, verbose_name="تاریخ فاکتور"
                    ),
                ),
                (
                    "sale_dailyprice",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="نرخ روز فروش"
                    ),
                ),
                (
                    "total_amount",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="مجموع مبلغ"
                    ),
                ),
                (
                    "discount",
                    models.IntegerField(blank=True, null=True, verbose_name="تخفیف"),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="شرح")),
                (
                    "companyseller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.companyseller",
                        verbose_name="کارشناس فروش",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="paniavault.customer",
                        verbose_name="مشتری",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OldGold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="کد کار",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="نام کالا"
                    ),
                ),
                (
                    "net_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="وزن خالص",
                    ),
                ),
                (
                    "weight_with_accessory",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="وزن با متعلقات",
                    ),
                ),
                (
                    "buy_price",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="قیمت خرید"
                    ),
                ),
                (
                    "buy_date",
                    django_jalali.db.models.jDateField(
                        blank=True, null=True, verbose_name="تاریخ خرید"
                    ),
                ),
                (
                    "buy_dailyprice",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="نرخ روز طلا"
                    ),
                ),
                (
                    "sale_price",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="قیمت فروش"
                    ),
                ),
                (
                    "sale_date",
                    django_jalali.db.models.jDateField(
                        blank=True, null=True, verbose_name="تاریخ فروش"
                    ),
                ),
                (
                    "sale_ojrat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="اجرت فروش",
                    ),
                ),
                (
                    "sale_tax",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="مالیات فروش"
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="شرح")),
                (
                    "is_sold",
                    models.BooleanField(default=False, verbose_name="وضعیت فروش"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="oldgold_image/",
                        verbose_name="تصویر بند انگشتی",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="old_supllier",
                        to="paniavault.supplier",
                        verbose_name="تأمین\u200cکننده",
                    ),
                ),
                (
                    "sale_invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="old_golds",
                        to="vitrin.saleinvoice",
                        verbose_name="فاکتور فروش",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CraftedGold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gold_type",
                    models.CharField(
                        choices=[
                            ("ring", "انگشتر"),
                            ("set", "ست و نیم ست"),
                            ("minimal", "مینیمال"),
                            ("earring", "گوشواره"),
                            ("bracelet", "دستبند"),
                            ("child", "کودک"),
                        ],
                        max_length=50,
                        verbose_name="دسته بندی",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="کد کار",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="نام کالا"
                    ),
                ),
                (
                    "net_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="وزن خالص",
                    ),
                ),
                (
                    "weight_with_accessory",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="وزن با متعلقات",
                    ),
                ),
                (
                    "buy_price",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="قیمت خرید"
                    ),
                ),
                (
                    "buy_date",
                    django_jalali.db.models.jDateField(
                        blank=True, null=True, verbose_name="تاریخ خرید"
                    ),
                ),
                (
                    "buy_ojrat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="اجرت خرید",
                    ),
                ),
                (
                    "buy_dailyprice",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="نرخ روز طلا"
                    ),
                ),
                (
                    "sale_price",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="قیمت فروش"
                    ),
                ),
                (
                    "sale_date",
                    django_jalali.db.models.jDateField(
                        blank=True, null=True, verbose_name="تاریخ فروش"
                    ),
                ),
                (
                    "sale_ojrat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="اجرت فروش",
                    ),
                ),
                (
                    "sale_tax",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="مالیات فروش"
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="شرح")),
                (
                    "is_sold",
                    models.BooleanField(default=False, verbose_name="وضعیت فروش"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="craftedgold_image/",
                        verbose_name="تصویر بند انگشتی",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crafted_supllier",
                        to="paniavault.supplier",
                        verbose_name="تأمین\u200cکننده",
                    ),
                ),
                (
                    "sale_invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crafted_golds",
                        to="vitrin.saleinvoice",
                        verbose_name="فاکتور فروش",
                    ),
                ),
            ],
        ),
    ]
