# Generated by Django 5.1.3 on 2025-01-08 12:43

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vitrin", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VitrinVault",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vitrin_type",
                    models.CharField(
                        choices=[("bajestan", "بجستان"), ("tehran", "تهران")],
                        max_length=20,
                        verbose_name="نوع ویترین",
                    ),
                ),
                (
                    "vitrin_balance",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0.00"),
                        max_digits=20,
                        verbose_name="موجودی ویترین",
                    ),
                ),
                (
                    "vitrin_assets",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        default=Decimal("0.00"),
                        max_digits=20,
                        null=True,
                        verbose_name="دارایی ویترین",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="شرح")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاریخ ایجاد"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="تاریخ به\u200cروزرسانی",
                    ),
                ),
            ],
        ),
    ]
