# Generated by Django 5.1.3 on 2025-01-09 05:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "paniavault",
            "0013_companyvault_vitrin_type_alter_meltpiece_invoice_and_more",
        ),
        ("vitrin", "0002_vitrinvault"),
    ]

    operations = [
        migrations.DeleteModel(
            name="VitrinVault",
        ),
    ]
