# Generated by Django 5.1.3 on 2025-01-09 14:07

import django.db.models.deletion
import django.utils.timezone
import django_jalali.db.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("paniavault", "0016_alter_reciptcraftinvoice_options_and_more"),
        ("vitrin", "0003_delete_vitrinvault"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyVitrin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vitrin_type",
                    models.CharField(
                        blank=True,
                        choices=[("vitrin", "بجستان"), ("safebox", "تهران")],
                        max_length=20,
                        null=True,
                        verbose_name="نوع ویترین",
                    ),
                ),
                (
                    "vitrin_balance",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0.00"),
                        max_digits=20,
                        verbose_name="موجودی ویترین",
                    ),
                ),
                (
                    "vitrin_assets",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        default=Decimal("0.00"),
                        max_digits=20,
                        null=True,
                        verbose_name="دارایی ویترین",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="شرح")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاریخ ایجاد"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="تاریخ به\u200cروزرسانی",
                    ),
                ),
            ],
        ),
        migrations.RenameModel(
            old_name="OldGold",
            new_name="OldPiece",
        ),
        migrations.CreateModel(
            name="CraftPiece",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gold_type",
                    models.CharField(
                        choices=[
                            ("ring", "انگشتر"),
                            ("set", "ست و نیم ست"),
                            ("minimal", "مینیمال"),
                            ("earring", "گوشواره"),
                            ("bracelet", "دستبند"),
                            ("child", "کودک"),
                        ],
                        max_length=50,
                        verbose_name="دسته بندی",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="کد کار",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="نام کالا"
                    ),
                ),
                (
                    "net_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="وزن خالص",
                    ),
                ),
                (
                    "weight_with_accessory",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="وزن با متعلقات",
                    ),
                ),
                (
                    "buy_price",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="قیمت خرید"
                    ),
                ),
                (
                    "buy_date",
                    django_jalali.db.models.jDateField(
                        blank=True, null=True, verbose_name="تاریخ خرید"
                    ),
                ),
                (
                    "buy_ojrat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="اجرت خرید",
                    ),
                ),
                (
                    "buy_dailyprice",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="نرخ روز طلا"
                    ),
                ),
                (
                    "sale_price",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="قیمت فروش"
                    ),
                ),
                (
                    "sale_date",
                    django_jalali.db.models.jDateField(
                        blank=True, null=True, verbose_name="تاریخ فروش"
                    ),
                ),
                (
                    "sale_ojrat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="اجرت فروش",
                    ),
                ),
                (
                    "sale_tax",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="مالیات فروش"
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="شرح")),
                (
                    "is_sold",
                    models.BooleanField(default=False, verbose_name="وضعیت فروش"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="craftedgold_image/",
                        verbose_name="تصویر بند انگشتی",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="caft_pieces",
                        to="paniavault.reciptcraftinvoice",
                        verbose_name="فاکتور بنکدار",
                    ),
                ),
                (
                    "sale_invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crafted_golds",
                        to="vitrin.saleinvoice",
                        verbose_name="فاکتور فروش",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crafted_supllier",
                        to="paniavault.supplier",
                        verbose_name="تأمین\u200cکننده",
                    ),
                ),
                (
                    "vitrin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="caft_vitrin",
                        to="vitrin.companyvitrin",
                        verbose_name="ویترین",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MeltPiece",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="کد کار",
                    ),
                ),
                (
                    "net_weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="وزن خالص قطعه",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="وزن قطعه"
                    ),
                ),
                (
                    "karat",
                    models.DecimalField(
                        decimal_places=0, max_digits=3, verbose_name="عیارقطعه"
                    ),
                ),
                (
                    "ang_number",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="شماره انگ"
                    ),
                ),
                (
                    "lab_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="نام آزمایشگاه",
                    ),
                ),
                (
                    "is_sold",
                    models.BooleanField(default=False, verbose_name="وضعیت فروش"),
                ),
                (
                    "additional_info",
                    models.TextField(
                        blank=True, null=True, verbose_name="اطلاعات اضافی"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاریخ ایجاد"
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="melt_pieces",
                        to="paniavault.reciptmeltinvoice",
                        verbose_name="فاکتور بنکدار",
                    ),
                ),
                (
                    "vitrin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="melt_vitrin",
                        to="vitrin.companyvitrin",
                        verbose_name="ویترین",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="CraftedGold",
        ),
    ]
