# Generated by Django 5.1.3 on 2025-01-10 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vitrin", "0005_alter_craftpiece_gold_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="meltpiece",
            name="sale_invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="melt_golds",
                to="vitrin.saleinvoice",
                verbose_name="فاکتور فروش آبشده",
            ),
        ),
    ]
