# Generated by Django 5.1.3 on 2025-01-10 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("paniavault", "0018_alter_buyrawinvoice_vault"),
        ("vitrin", "0006_meltpiece_sale_invoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="meltpiece",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meltpiece_supllier",
                to="paniavault.supplier",
                verbose_name="تأمین\u200cکننده",
            ),
        ),
        migrations.AlterField(
            model_name="craftpiece",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="craftedpiece_supllier",
                to="paniavault.supplier",
                verbose_name="تأمین\u200cکننده",
            ),
        ),
    ]
