# Generated by Django 5.1.3 on 2025-01-10 12:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vitrin", "0007_meltpiece_supplier_alter_craftpiece_supplier"),
    ]

    operations = [
        migrations.AddField(
            model_name="craftpiece",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="تاریخ ایجاد"
            ),
        ),
        migrations.AddField(
            model_name="oldpiece",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="تاریخ ایجاد"
            ),
        ),
    ]
