# Generated by Django 5.1.3 on 2025-01-12 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vitrin", "0008_craftpiece_created_at_oldpiece_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="oldpiece",
            name="vitrin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="old_vitrin",
                to="vitrin.companyvitrin",
                verbose_name="ویترین",
            ),
        ),
        migrations.AlterField(
            model_name="oldpiece",
            name="sale_invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="old_piece",
                to="vitrin.saleinvoice",
                verbose_name="فاکتور فروش",
            ),
        ),
    ]
