# Generated by Django 5.1.3 on 2025-01-13 09:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vitrin", "0009_oldpiece_vitrin_alter_oldpiece_sale_invoice"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="craftpiece",
            options={
                "verbose_name": "طلای زینتی",
                "verbose_name_plural": "طلاهای زینتی",
            },
        ),
        migrations.AlterModelOptions(
            name="meltpiece",
            options={
                "verbose_name": "طلای آبشده",
                "verbose_name_plural": "طلاهای آبشده",
            },
        ),
        migrations.AlterModelOptions(
            name="oldpiece",
            options={
                "verbose_name": "طلای مستعمل",
                "verbose_name_plural": "طلاهای مستعمل",
            },
        ),
        migrations.AddField(
            model_name="companyvitrin",
            name="vitrin_ojrat_balance",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0.00"),
                max_digits=20,
                verbose_name="موجودی اجرت ویترین",
            ),
        ),
        migrations.AlterField(
            model_name="meltpiece",
            name="net_weight",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="وزن عیار 750",
            ),
        ),
    ]
