# Generated by Django 5.1.3 on 2025-01-14 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("paniavault", "0018_alter_buyrawinvoice_vault"),
        ("vitrin", "0010_alter_craftpiece_options_alter_meltpiece_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oldpiece",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="old_supllier",
                to="paniavault.customer",
                verbose_name="تأمین\u200cکننده",
            ),
        ),
    ]
