# Generated by Django 5.1.3 on 2025-01-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vitrin", "0011_alter_oldpiece_supplier"),
    ]

    operations = [
        migrations.AddField(
            model_name="meltpiece",
            name="name",
            field=models.CharField(
                blank=True,
                default="آبشده",
                max_length=50,
                null=True,
                verbose_name="نام کالا",
            ),
        ),
        migrations.AlterField(
            model_name="meltpiece",
            name="code",
            field=models.CharField(
                blank=True, max_length=50, null=True, unique=True, verbose_name="کد کار"
            ),
        ),
    ]
