# Generated by Django 5.1.3 on 2025-01-16 19:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vitrin", "0012_meltpiece_name_alter_meltpiece_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="meltpiece",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="meltgold_image/",
                verbose_name="تصویر بند انگشتی",
            ),
        ),
    ]
