# Generated by Django 5.1.3 on 2025-01-30 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_companyseller_homeimage"),
        (
            "paniavault",
            "0022_alter_customer_address_alter_customer_code_posti_and_more",
        ),
        ("vitrin", "0014_rename_total_amount_saleinvoice_sale_price_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="saleinvoice",
            options={
                "verbose_name": "فاکتور فروش",
                "verbose_name_plural": "فاکتورهای فروش",
            },
        ),
        migrations.AlterField(
            model_name="craftpiece",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="craft_pieces",
                to="paniavault.reciptcraftinvoice",
                verbose_name="فاکتور بنکدار",
            ),
        ),
        migrations.AlterField(
            model_name="craftpiece",
            name="vitrin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="craft_vitrin",
                to="vitrin.companyvitrin",
                verbose_name="ویترین",
            ),
        ),
        migrations.AlterField(
            model_name="oldpiece",
            name="sale_invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="old_gold",
                to="vitrin.saleinvoice",
                verbose_name="فاکتور فروش مستعمل",
            ),
        ),
        migrations.AlterField(
            model_name="saleinvoice",
            name="companyseller",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.companyseller",
                verbose_name="کارشناس فروش",
            ),
        ),
        migrations.AlterField(
            model_name="saleinvoice",
            name="sale_price",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="مجموع مبلغ فاکتور"
            ),
        ),
    ]
