# Generated by Django 5.1.3 on 2025-02-04 07:13

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vitrin", "0015_alter_saleinvoice_options_alter_craftpiece_invoice_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="saleinvoice",
            options={
                "verbose_name": "فاکتور فروش",
                "verbose_name_plural": "فاکتور فروش زینتی و مستعمل",
            },
        ),
        migrations.AddField(
            model_name="meltpiece",
            name="sale_date",
            field=django_jalali.db.models.jDateField(
                blank=True, null=True, verbose_name="تاریخ فروش"
            ),
        ),
        migrations.AddField(
            model_name="meltpiece",
            name="sale_ojrat",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=15,
                null=True,
                verbose_name="اجرت فروش",
            ),
        ),
        migrations.AddField(
            model_name="meltpiece",
            name="sale_price",
            field=models.IntegerField(blank=True, null=True, verbose_name="قیمت فروش"),
        ),
        migrations.AddField(
            model_name="meltpiece",
            name="sale_tax",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="مالیات فروش"
            ),
        ),
        migrations.AlterField(
            model_name="craftpiece",
            name="buy_dailyprice",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="نرخ روز خرید"
            ),
        ),
        migrations.AlterField(
            model_name="craftpiece",
            name="gold_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ring", "انگشتر"),
                    ("set", "ست و نیم ست"),
                    ("minimal", "مینیمال"),
                    ("earring", "گوشواره"),
                    ("bracelet", "دستبند"),
                    ("necklace", "گردنبند"),
                    ("child", "کودک"),
                ],
                max_length=50,
                null=True,
                verbose_name="دسته بندی",
            ),
        ),
        migrations.AlterField(
            model_name="oldpiece",
            name="buy_dailyprice",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="نرخ روز خرید"
            ),
        ),
    ]
