# Generated by Django 5.1.3 on 2025-02-06 17:23

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_companyseller_homeimage"),
        (
            "paniavault",
            "0022_alter_customer_address_alter_customer_code_posti_and_more",
        ),
        ("vitrin", "0016_alter_saleinvoice_options_meltpiece_sale_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SaleMeltInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sale_date",
                    django_jalali.db.models.jDateField(
                        blank=True, null=True, verbose_name="تاریخ فاکتور"
                    ),
                ),
                (
                    "sale_dailyprice",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="نرخ روز فروش"
                    ),
                ),
                (
                    "sale_price",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="مجموع مبلغ فاکتور"
                    ),
                ),
                (
                    "sale_tax",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="جمع مالیات"
                    ),
                ),
                (
                    "discount",
                    models.IntegerField(blank=True, null=True, verbose_name="تخفیف"),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="شرح")),
                (
                    "companyseller",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.companyseller",
                        verbose_name="کارشناس فروش",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="paniavault.customer",
                        verbose_name="مشتری",
                    ),
                ),
            ],
            options={
                "verbose_name": "فاکتور فروش آبشده",
                "verbose_name_plural": "فاکتور فروش آبشده",
            },
        ),
        migrations.AlterField(
            model_name="meltpiece",
            name="sale_invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="melt_golds",
                to="vitrin.salemeltinvoice",
                verbose_name="فاکتور فروش آبشده",
            ),
        ),
    ]
