# Generated by Django 5.1.3 on 2025-02-06 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vitrin", "0018_alter_meltpiece_sale_invoice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meltpiece",
            name="sale_invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="melt_golds",
                to="vitrin.salemeltinvoice",
                verbose_name="فاکتور فروش آبشده",
            ),
        ),
    ]
