# Generated by Django 5.1.3 on 2025-02-07 03:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vitrin", "0019_alter_meltpiece_sale_invoice"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="saleinvoice",
            options={
                "verbose_name": "فاکتور فروش",
                "verbose_name_plural": "فاکتور فروش زینتی ",
            },
        ),
        migrations.RenameField(
            model_name="salemeltinvoice",
            old_name="sale_price",
            new_name="total_sale_price",
        ),
    ]
