# Generated by Django 5.1.3 on 2025-02-20 09:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vitrin", "0020_alter_saleinvoice_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="salemeltinvoice",
            name="companyseller",
        ),
        migrations.RemoveField(
            model_name="salemeltinvoice",
            name="customer",
        ),
        migrations.DeleteModel(
            name="MeltPiece",
        ),
        migrations.DeleteModel(
            name="SaleMeltInvoice",
        ),
    ]
