# Generated by Django 5.1.3 on 2025-03-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vitrin", "0021_remove_salemeltinvoice_companyseller_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="saleinvoice",
            name="total_paid",
            field=models.BigIntegerField(
                default=0, verbose_name="جمع پرداخت\u200cهای مشتری"
            ),
        ),
    ]
