# Generated by Django 5.1.3 on 2025-03-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vitrin", "0022_saleinvoice_total_paid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="craftpiece",
            name="gold_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ring", "انگشتر"),
                    ("set", "ست و نیم ست"),
                    ("minimal", "مینیمال"),
                    ("earring", "گوشواره"),
                    ("bracelet", "دستبند"),
                    ("necklace", "گردنبند"),
                    ("kids", "کودک"),
                    ("coin", "سکه"),
                ],
                max_length=50,
                null=True,
                verbose_name="دسته بندی",
            ),
        ),
    ]
