# Generated by Django 5.1.3 on 2025-04-07 18:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vitrin", "0023_alter_craftpiece_gold_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="craftpiece",
            options={
                "verbose_name": "طلای زینتی",
                "verbose_name_plural": "ویترین زینتی",
            },
        ),
        migrations.AlterModelOptions(
            name="oldpiece",
            options={
                "verbose_name": "طلای  مستعمل",
                "verbose_name_plural": "ویترین مستعمل",
            },
        ),
        migrations.AlterModelOptions(
            name="saleinvoice",
            options={
                "verbose_name": "فاکتور فروش",
                "verbose_name_plural": "فاکتورهای فروش زینتی و مستعمل ",
            },
        ),
    ]
