# Generated by Django 5.1.3 on 2025-04-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vitrin", "0024_alter_craftpiece_options_alter_oldpiece_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="craftpiece",
            name="buy_price_ojrat",
            field=models.IntegerField(default=0, verbose_name="اجرت ریالی خرید"),
        ),
        migrations.AddField(
            model_name="craftpiece",
            name="sale_price_ojrat",
            field=models.IntegerField(default=0, verbose_name="اجرت ریالی فروش"),
        ),
    ]
