# Generated by Django 5.1.3 on 2025-04-14 02:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vitrin", "0025_craftpiece_buy_price_ojrat_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="saleinvoice",
            name="net_sale_price",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="خالص مبلغ فاکتور"
            ),
        ),
    ]
