# Generated by Django 5.1.3 on 2025-04-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vitrin", "0027_oldpiece_sale_price_ojrat"),
    ]

    operations = [
        migrations.AddField(
            model_name="saleinvoice",
            name="invoice_serial",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="سریال فاکتور"
            ),
        ),
        migrations.AlterField(
            model_name="saleinvoice",
            name="sale_price",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="جمع مبلغ فاکتور"
            ),
        ),
    ]
