# Generated by Django 5.1.3 on 2025-04-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vitrin", "0028_saleinvoice_invoice_serial_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="saleinvoice",
            options={
                "verbose_name": "فاکتور فروش زینتی و مستعمل",
                "verbose_name_plural": "فاکتورهای فروش زینتی و مستعمل ",
            },
        ),
        migrations.AlterField(
            model_name="saleinvoice",
            name="invoice_serial",
            field=models.TextField(blank=True, null=True, verbose_name="سریال فاکتور"),
        ),
    ]
