# Generated by Django 5.1.3 on 2025-04-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vitrin", "0029_alter_saleinvoice_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oldpiece",
            name="sale_ojrat",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=15,
                null=True,
                verbose_name="اجرت فروش",
            ),
        ),
    ]
