# Generated by Django 5.1.3 on 2025-04-27 02:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vitrin", "0030_alter_oldpiece_sale_ojrat"),
    ]

    operations = [
        migrations.AddField(
            model_name="craftpiece",
            name="seller_profit_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=7.0,
                max_digits=5,
                verbose_name="درصد سود فروشنده",
            ),
        ),
        migrations.AddField(
            model_name="oldpiece",
            name="seller_profit_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=7.0,
                max_digits=5,
                verbose_name="درصد سود فروشنده",
            ),
        ),
    ]
