# Generated by Django 5.1.3 on 2025-04-30 06:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vitrin", "0031_craftpiece_seller_profit_percent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="craftpiece",
            name="buy_ojrat",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=15,
                null=True,
                verbose_name="اجرت خرید",
            ),
        ),
        migrations.AlterField(
            model_name="craftpiece",
            name="sale_ojrat",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=15,
                null=True,
                verbose_name="اجرت فروش",
            ),
        ),
        migrations.AlterField(
            model_name="craftpiece",
            name="seller_profit_percent",
            field=models.DecimalField(
                decimal_places=1,
                default=7.0,
                max_digits=5,
                verbose_name="درصد سود فروشنده",
            ),
        ),
        migrations.AlterField(
            model_name="oldpiece",
            name="sale_ojrat",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                default=0,
                max_digits=15,
                null=True,
                verbose_name="اجرت فروش",
            ),
        ),
        migrations.AlterField(
            model_name="oldpiece",
            name="seller_profit_percent",
            field=models.DecimalField(
                decimal_places=1,
                default=7.0,
                max_digits=5,
                verbose_name="درصد سود فروشنده",
            ),
        ),
    ]
