# Generated by Django 5.1.3 on 2025-05-04 07:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vitrin", "0032_alter_craftpiece_buy_ojrat_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="craftpiece",
            name="buy_ojrat",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                default=0,
                max_digits=15,
                verbose_name="اجرت خرید",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="craftpiece",
            name="sale_ojrat",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                default=0,
                max_digits=15,
                verbose_name="اجرت فروش",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="oldpiece",
            name="sale_ojrat",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                default=0,
                max_digits=15,
                verbose_name="اجرت فروش",
            ),
        ),
    ]
