# Generated by Django 5.1.3 on 2025-05-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vitrin", "0034_alter_craftpiece_buy_ojrat_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyvitrin",
            name="vitrin_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("vitrin1", "tehran"),
                    ("vitrin2", "bajestan"),
                    ("vitrin3", "abhar"),
                ],
                default="vitrin1",
                max_length=20,
                null=True,
                verbose_name="نوع ویترین",
            ),
        ),
    ]
