# Generated by Django 5.1.3 on 2025-03-05 10:36

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("vitrin", "0021_remove_salemeltinvoice_companyseller_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SaleInvoicePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.PositiveIntegerField(verbose_name="مبلغ پرداخت")),
                (
                    "discount",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="تخفیف "
                    ),
                ),
                (
                    "discount_code",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="کد تخفیف"
                    ),
                ),
                (
                    "etebar",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="اعتبار "
                    ),
                ),
                (
                    "etebar_code",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="کد اعتبار"
                    ),
                ),
                (
                    "pay_date",
                    django_jalali.db.models.jDateField(
                        blank=True, null=True, verbose_name="تاریخ پرداخت"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("نقدی", "نقدی"),
                            ("اعتباری", "اعتباری"),
                            ("تهاتر", "تهاتر"),
                        ],
                        max_length=50,
                        verbose_name="روش پرداخت",
                    ),
                ),
                (
                    "payment_explain",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="شرح پرداخت"
                    ),
                ),
                (
                    "payment_receipt",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="رسید پرداخت"
                    ),
                ),
                (
                    "payment_confirm",
                    models.BooleanField(default=False, verbose_name="تایید پرداخت"),
                ),
                (
                    "saleinvoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salepayments",
                        to="vitrin.saleinvoice",
                        verbose_name="پرداختی فروش زینتی",
                    ),
                ),
            ],
            options={
                "verbose_name": "پرداخت فروش زینتی",
                "verbose_name_plural": "پرداختهای فروش زینتی",
            },
        ),
    ]
