# Generated by Django 5.1.3 on 2025-03-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="saleinvoicepayment",
            name="payment_confirm",
        ),
        migrations.AlterField(
            model_name="saleinvoicepayment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("نقدی", "نقدی"),
                    ("اعتباری", "اعتباری"),
                    ("تهاتر", "تهاتر"),
                    ("تخفیف", "تخفیف"),
                ],
                max_length=50,
                verbose_name="روش پرداخت",
            ),
        ),
    ]
