# Generated by Django 5.1.3 on 2025-03-10 07:16

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0002_remove_saleinvoicepayment_payment_confirm_and_more"),
        ("meltvitrin", "0002_salemeltinvoice_total_paid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="saleinvoicepayment",
            name="pay_date",
            field=django_jalali.db.models.jDateField(verbose_name="تاریخ پرداخت"),
        ),
        migrations.AlterField(
            model_name="saleinvoicepayment",
            name="payment_receipt",
            field=models.CharField(max_length=50, verbose_name="رسید پرداخت"),
        ),
        migrations.CreateModel(
            name="SaleMeltInvoicePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.PositiveIntegerField(verbose_name="مبلغ پرداخت")),
                (
                    "discount",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="تخفیف "
                    ),
                ),
                (
                    "discount_code",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="کد تخفیف"
                    ),
                ),
                (
                    "etebar",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="اعتبار "
                    ),
                ),
                (
                    "etebar_code",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="کد اعتبار"
                    ),
                ),
                (
                    "pay_date",
                    django_jalali.db.models.jDateField(verbose_name="تاریخ پرداخت"),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("نقدی", "نقدی"),
                            ("اعتباری", "اعتباری"),
                            ("تهاتر", "تهاتر"),
                            ("تخفیف", "تخفیف"),
                        ],
                        max_length=50,
                        verbose_name="روش پرداخت",
                    ),
                ),
                (
                    "payment_explain",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="شرح پرداخت"
                    ),
                ),
                (
                    "payment_receipt",
                    models.CharField(max_length=50, verbose_name="رسید پرداخت"),
                ),
                (
                    "meltsaleinvoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meltsalepayments",
                        to="meltvitrin.salemeltinvoice",
                        verbose_name="پرداختی فروش آبشده",
                    ),
                ),
            ],
            options={
                "verbose_name": "پرداخت فروش آبشده",
                "verbose_name_plural": "پرداختهای فروش آبشده",
            },
        ),
    ]
