# Generated by Django 5.1.3 on 2025-04-07 18:29

import django.db.models.deletion
import django.utils.timezone
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0003_alter_saleinvoicepayment_pay_date_and_more"),
        ("paniavault", "0023_alter_buyrawinvoice_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salemeltinvoicepayment",
            name="pay_date",
            field=django_jalali.db.models.jDateField(
                blank=True, null=True, verbose_name="تاریخ پرداخت"
            ),
        ),
        migrations.CreateModel(
            name="BuyRawInvoicePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.PositiveIntegerField(verbose_name="مبلغ پرداخت")),
                (
                    "discount",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="تخفیف "
                    ),
                ),
                (
                    "discount_code",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="کد تخفیف"
                    ),
                ),
                (
                    "pay_date",
                    django_jalali.db.models.jDateField(
                        blank=True, null=True, verbose_name="تاریخ پرداخت"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("حساب رسمی", "حساب رسمی"),
                            ("حساب غیر رسمی", "حساب غیر رسمی"),
                        ],
                        max_length=50,
                        verbose_name="روش پرداخت",
                    ),
                ),
                (
                    "payment_place",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="حساب پرداخت",
                    ),
                ),
                (
                    "payment_explain",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="شرح پرداخت"
                    ),
                ),
                (
                    "payment_receipt",
                    models.CharField(max_length=50, verbose_name="رسید پرداخت"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاریخ ایجاد"
                    ),
                ),
                (
                    "buyrawinvoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buyrawpayments",
                        to="paniavault.buyrawinvoice",
                        verbose_name="پرداختی خرید خام",
                    ),
                ),
            ],
            options={
                "verbose_name": "پرداختی خرید خام",
                "verbose_name_plural": "پرداختیهای خرید خام",
            },
        ),
    ]
