# Generated by Django 5.1.3 on 2025-04-23 12:19

import django.db.models.deletion
import django.utils.timezone
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0004_alter_salemeltinvoicepayment_pay_date_and_more"),
        ("vitrin", "0030_alter_oldpiece_sale_ojrat"),
    ]

    operations = [
        migrations.CreateModel(
            name="OldPiecePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.PositiveIntegerField(verbose_name="مبلغ پرداخت")),
                (
                    "discount",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="تخفیف "
                    ),
                ),
                (
                    "discount_code",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="کد تخفیف"
                    ),
                ),
                (
                    "pay_date",
                    django_jalali.db.models.jDateField(
                        blank=True, null=True, verbose_name="تاریخ پرداخت"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("حساب رسمی", "حساب رسمی"),
                            ("حساب غیر رسمی", "حساب غیر رسمی"),
                        ],
                        max_length=50,
                        verbose_name="روش پرداخت",
                    ),
                ),
                (
                    "payment_place",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="حساب پرداخت",
                    ),
                ),
                (
                    "payment_explain",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="شرح پرداخت"
                    ),
                ),
                (
                    "payment_receipt",
                    models.CharField(max_length=50, verbose_name="رسید پرداخت"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاریخ ایجاد"
                    ),
                ),
                (
                    "oldpiece",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oldpiecepayments",
                        to="vitrin.oldpiece",
                        verbose_name="پرداختی خرید مستعمل",
                    ),
                ),
            ],
            options={
                "verbose_name": "پرداختی خرید مستعمل",
                "verbose_name_plural": "پرداختیهای خرید مستعمل",
            },
        ),
    ]
