# Generated by Django 5.1.3 on 2025-05-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0005_oldpiecepayment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oldpiecepayment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("حساب رسمی", "حساب رسمی"),
                    ("حساب غیر رسمی", "حساب غیر رسمی"),
                    ("تهاتر", "تهاتر"),
                ],
                max_length=50,
                verbose_name="روش پرداخت",
            ),
        ),
    ]
