# Generated by Django 5.1.3 on 2025-02-20 09:01

import django.db.models.deletion
import django.utils.timezone
import django_jalali.db.models
import meltvitrin.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0002_companyseller_homeimage"),
        (
            "paniavault",
            "0022_alter_customer_address_alter_customer_code_posti_and_more",
        ),
        ("vitrin", "0021_remove_salemeltinvoice_companyseller_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SaleMeltInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sale_date",
                    django_jalali.db.models.jDateField(
                        blank=True, null=True, verbose_name="تاریخ فاکتور"
                    ),
                ),
                (
                    "sale_dailyprice",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="نرخ روز فروش"
                    ),
                ),
                (
                    "total_sale_price",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="مجموع مبلغ فاکتور"
                    ),
                ),
                (
                    "sale_tax",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="جمع مالیات"
                    ),
                ),
                (
                    "discount",
                    models.IntegerField(blank=True, null=True, verbose_name="تخفیف"),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="شرح")),
                (
                    "companyseller",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.companyseller",
                        verbose_name="کارشناس فروش",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="paniavault.customer",
                        verbose_name="مشتری",
                    ),
                ),
            ],
            options={
                "verbose_name": "فاکتور فروش آبشده",
                "verbose_name_plural": "فاکتور فروش آبشده",
            },
        ),
        migrations.CreateModel(
            name="MeltPiece",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="آبشده",
                        max_length=50,
                        null=True,
                        verbose_name="نام کالا",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="کد کار",
                    ),
                ),
                (
                    "net_weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="وزن عیار 750",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="وزن قطعه"
                    ),
                ),
                (
                    "karat",
                    models.DecimalField(
                        decimal_places=0, max_digits=3, verbose_name="عیارقطعه"
                    ),
                ),
                (
                    "ang_number",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="شماره انگ"
                    ),
                ),
                (
                    "lab_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="نام آزمایشگاه",
                    ),
                ),
                (
                    "is_sold",
                    models.BooleanField(default=False, verbose_name="وضعیت فروش"),
                ),
                (
                    "sale_price",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="قیمت فروش"
                    ),
                ),
                (
                    "sale_date",
                    django_jalali.db.models.jDateField(
                        blank=True, null=True, verbose_name="تاریخ فروش"
                    ),
                ),
                (
                    "sale_ojrat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="اجرت فروش",
                    ),
                ),
                (
                    "sale_tax",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="مالیات فروش"
                    ),
                ),
                (
                    "additional_info",
                    models.TextField(
                        blank=True, null=True, verbose_name="اطلاعات اضافی"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=meltvitrin.models.upload_to_melt,
                        verbose_name="تصویر بند انگشتی",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاریخ ایجاد"
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="melt_pieces",
                        to="paniavault.reciptmeltinvoice",
                        verbose_name="فاکتور بنکدار",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meltpiece_supllier",
                        to="paniavault.supplier",
                        verbose_name="تأمین\u200cکننده",
                    ),
                ),
                (
                    "vitrin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="melt_vitrin",
                        to="vitrin.companyvitrin",
                        verbose_name="ویترین",
                    ),
                ),
                (
                    "sale_invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="melt_golds",
                        to="meltvitrin.salemeltinvoice",
                        verbose_name="فاکتور فروش آبشده",
                    ),
                ),
            ],
            options={
                "verbose_name": "طلای آبشده",
                "verbose_name_plural": "طلاهای آبشده",
            },
        ),
    ]
