# Generated by Django 5.1.3 on 2025-03-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meltvitrin", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="salemeltinvoice",
            name="total_paid",
            field=models.BigIntegerField(
                default=0, verbose_name="جمع پرداخت\u200cهای مشتری"
            ),
        ),
    ]
