# Generated by Django 5.1.3 on 2025-04-07 18:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meltvitrin", "0002_salemeltinvoice_total_paid"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="meltpiece",
            options={
                "verbose_name": "طلای آبشده",
                "verbose_name_plural": "ویترین آبشده",
            },
        ),
        migrations.AlterModelOptions(
            name="salemeltinvoice",
            options={
                "verbose_name": "فاکتور فروش آبشده",
                "verbose_name_plural": "فاکتورهای فروش آبشده",
            },
        ),
    ]
