# Generated by Django 5.1.3 on 2025-04-08 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meltvitrin", "0003_alter_meltpiece_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="meltpiece",
            name="piece_type",
            field=models.CharField(
                choices=[("آبشده", "آبشده"), ("امانی", "امانی")],
                default="آبشده",
                max_length=20,
                verbose_name="نوع قطعه",
            ),
        ),
    ]
